apiVersion: v1
kind: Service
metadata:
  name: External Cloud Service Integration and Management
  labels:
    app: External Cloud Service Integration and Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: External Cloud Service Integration and Management