apiVersion: v1
kind: Service
metadata:
  name: Customer Relationship Management
  labels:
    app: Customer Relationship Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer Relationship Management