apiVersion: v1
kind: Service
metadata:
  name: Maintenance and Support Services
  labels:
    app: Maintenance and Support Services
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Maintenance and Support Services