---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hybrid Cloud Service Design and Development
  labels:
    app: Hybrid Cloud Service Design and Development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Hybrid Cloud Service Design and Development
  template:
    metadata:
      labels:
        app: Hybrid Cloud Service Design and Development
    spec:
      containers:
        - name: Hybrid Cloud Service Design and Development
          image: username/Hybrid Cloud Service Design and Development:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: External Cloud Service Integration and Management
  labels:
    app: External Cloud Service Integration and Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: External Cloud Service Integration and Management
  template:
    metadata:
      labels:
        app: External Cloud Service Integration and Management
    spec:
      containers:
        - name: External Cloud Service Integration and Management
          image: username/External Cloud Service Integration and Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Security Management and Monitoring
  labels:
    app: Security Management and Monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Security Management and Monitoring
  template:
    metadata:
      labels:
        app: Security Management and Monitoring
    spec:
      containers:
        - name: Security Management and Monitoring
          image: username/Security Management and Monitoring:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Customer Relationship Management
  labels:
    app: Customer Relationship Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customer Relationship Management
  template:
    metadata:
      labels:
        app: Customer Relationship Management
    spec:
      containers:
        - name: Customer Relationship Management
          image: username/Customer Relationship Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Maintenance and Support Services
  labels:
    app: Maintenance and Support Services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Maintenance and Support Services
  template:
    metadata:
      labels:
        app: Maintenance and Support Services
    spec:
      containers:
        - name: Maintenance and Support Services
          image: username/Maintenance and Support Services:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Hybrid Cloud Service Design and Development
  labels:
    app: Hybrid Cloud Service Design and Development
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Hybrid Cloud Service Design and Development


---


apiVersion: v1
kind: Service
metadata:
  name: External Cloud Service Integration and Management
  labels:
    app: External Cloud Service Integration and Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: External Cloud Service Integration and Management


---


apiVersion: v1
kind: Service
metadata:
  name: Security Management and Monitoring
  labels:
    app: Security Management and Monitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Security Management and Monitoring


---


apiVersion: v1
kind: Service
metadata:
  name: Customer Relationship Management
  labels:
    app: Customer Relationship Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer Relationship Management


---


apiVersion: v1
kind: Service
metadata:
  name: Maintenance and Support Services
  labels:
    app: Maintenance and Support Services
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Maintenance and Support Services

