apiVersion: v1
kind: Service
metadata:
  name: Security Management and Monitoring
  labels:
    app: Security Management and Monitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Security Management and Monitoring